Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 512
        vb.check_guest_additions = false
    end

    config.vm.provision "shell", path: "scripts/install-utils.sh"
    config.vm.provision "shell", path: "scripts/install-kubectl.sh"

    config.vm.define "server" do |server|
        server.vm.box = "debian/bookworm64"
        server.vm.box_version = "12.20250126.1"
        server.vm.hostname = "alefrancS"

        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provision "shell", path: "scripts/set-controller-mode.sh"
    end

    config.vm.define "worker" do |worker|
        worker.vm.box = "debian/bookworm64"
        worker.vm.box_version = "12.20250126.1"
        worker.vm.hostname = "alefrancSW"

        worker.vm.network "private_network", ip: "192.168.56.111"

        worker.vm.provision "shell", path: "scripts/set-agent-mode.sh"
    end
end
